apiVersion: apps/v1
kind: Deployment
metadata:
  name: result
  namespace: voting-app
  labels:
    app: result
spec:
  replicas: 2
  selector:
    matchLabels:
      app: result
  template:
    metadata:
      labels:
        app: result
    spec:
      containers:
      - name: result
        image: hiiamgay/result:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
        env:
        - name: PORT
          value: "80"
        - name: DATABASE_URL
          value: "postgres://postgres:postgres@db/postgres"
        resources:
          limits:
            cpu: "200m"
            memory: "256Mi"
          requests:
            cpu: "100m"
            memory: "128Mi"

---
apiVersion: v1
kind: Service
metadata:
  name: result
  namespace: voting-app
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "80"  # Cổng container đang chạy ứng dụng
    prometheus.io/path: "/metrics"
  labels:
    app: result
spec:
  selector:
    app: result
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: ClusterIP
