apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker
  namespace: voting-app
  labels:
    app: worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: worker
  template:
    metadata:
      labels:
        app: worker
    spec:
      containers:
      - name: worker
        image: hiiamgay/worker:latest
        imagePullPolicy: IfNotPresent
        env:
        - name: REDIS_HOST
          value: "redis"
        - name: DB_HOST
          value: "db"
        - name: ASPNETCORE_ENVIRONMENT
          value: "Production"
        resources:
          limits:
            cpu: "150m"
            memory: "192Mi"
          requests:
            cpu: "100m"
            memory: "128Mi"

---
apiVersion: v1
kind: Service
metadata:
  name: worker
  namespace: voting-app
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "80"  # Cổng container đang chạy ứng dụng
    prometheus.io/path: "/metrics"
  labels:
    app: worker
spec:
  selector:
    app: worker
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: ClusterIP
